version: '3.8'

services:
  # Serviço PostgreSQL para o Spring Boot se conectar
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres_voluntariado
    environment:
      # Credenciais do Banco
      POSTGRES_USER: voluntario_user
      POSTGRES_PASSWORD: voluntario_password
      POSTGRES_DB: voluntariado_db
    ports:
      # Porta que o seu Spring Boot irá acessar o Postgres (Padrão: 5432)
      - "5432:5432"
    volumes:
      # Persistência dos dados
      - postgres_data:/var/lib/postgresql/data

  # Serviço LocalStack (Simula o S3 e outros serviços AWS)
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_voluntariado
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=s3,sqs
      - DEFAULT_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      # Mapeamento do script de inicialização do S3
      - ./localstack/init:/etc/localstack/init/ready.d

volumes:
  postgres_data: