version: '3.8'
services:
  app:
    build: .
    container_name: voluntariado-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-Xmx450m

      # Banco de Dados
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/voluntariado_db
      - SPRING_DATASOURCE_USERNAME=voluntario_user
      - SPRING_DATASOURCE_PASSWORD=senha_segura_producao

      # --- CONFIGURAÇÃO ORACLE S3 ---
      - AWS_REGION=sa-saopaulo-1
      - AWS_S3_ENDPOINT_URL=https://gri2dbzfssib.compat.objectstorage.sa-saopaulo-1.oraclecloud.com
      - AWS_S3_BUCKET_NAME=voluntariado-antecedentes-bucket

      # Correção: Passando com o nome da variável do Java E do Sistema para garantir
      - AWS_ACCESS_KEY_ID='AWS_ACCESS_KEY_ID'
      - AWS_SECRET_ACCESS_KEY='AWS_SECRET_ACCESS_KEY'

      # Redundância para o Java pegar direto (caso o properties falhe)
      - AWS_ACCESS_KEY='AWS_ACCESS_KEY'
      - AWS_SECRET_KEY='AWS_SECRET_ACCESS_KEY'

      # --- CONFIGURAÇÃO E-MAIL ---
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=leomelolima86@gmail.com
      # CORREÇÃO: Aspas obrigatórias aqui por causa dos espaços
      - SPRING_MAIL_PASSWORD=SPRING_MAIL_PASSWORD
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: voluntariado-db
    restart: always
    environment:
      - POSTGRES_USER=voluntario_user
      - POSTGRES_PASSWORD=senha_segura_producao
      - POSTGRES_DB=voluntariado_db
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

volumes:
  postgres_data_prod: